/// Country calling codes for phone number input.
class CountryDialCode {
  const CountryDialCode({
    required this.isoCode,
    required this.name,
    required this.dialCode,
    required this.flag,
  });

  final String isoCode;
  final String name;
  final String dialCode;
  final String flag;

  static const _abbreviations = {
    'AE': 'UAE',
    'AG': 'A&B',
    'AS': 'Am. Samoa',
    'BA': 'BiH',
    'BF': 'Burkina',
    'CD': 'DRC',
    'CF': 'CAR',
    'CI': 'IC',
    'CR': 'CR',
    'CV': 'CV',
    'DO': 'DR',
    'FK': 'Falklands',
    'FO': 'Faroe Is.',
    'GB': 'UK',
    'GF': 'Fr. Guiana',
    'GQ': 'Eq. Guinea',
    'GW': 'GN-B',
    'HK': 'HK',
    'IM': 'IOM',
    'IO': 'BIOT',
    'KP': 'N. Korea',
    'KR': 'S. Korea',
    'KY': 'Cayman',
    'LC': 'St Lucia',
    'LK': 'LK',
    'MH': 'Marshall Is.',
    'MK': 'N. Macedonia',
    'MP': 'N. Mariana Is.',
    'NC': 'NC',
    'NF': 'Norfolk Is.',
    'NZ': 'NZ',
    'PG': 'PNG',
    'PF': 'Fr. Polynesia',
    'PR': 'PR',
    'SA': 'KSA',
    'SB': 'Solomon Is.',
    'SH': 'St Helena',
    'SL': 'SL',
    'SM': 'SM',
    'SS': 'S. Sudan',
    'SV': 'ELS',
    'SX': 'SX',
    'TC': 'Turks & Caicos',
    'TL': 'TL',
    'TT': 'T&T',
    'US': 'USA',
    'VA': 'Vatican',
    'VG': 'BVI',
    'VI': 'USVI',
    'WF': 'Wallis & Futuna',
    'ZA': 'S. Africa',
    'BL': 'St Barthélemy',
    'CC': 'Cocos Is.',
    'CK': 'Cook Is.',
    'CX': 'Christmas Is.',
    'EH': 'W. Sahara',
    'KN': 'St Kitts',
    'MF': 'St Martin',
    'PM': 'St Pierre',
    'ST': 'São Tomé',
    'VC': 'St Vincent',
  };

  String get displayName {
    if (_abbreviations.containsKey(isoCode)) {
      return _abbreviations[isoCode]!;
    }
    if (!name.contains(' ') && !name.contains('-')) {
      return name;
    }
    const stopWords = {'and', 'of', 'the'};
    return name
        .split(RegExp(r'[\s\-]+'))
        .where((word) => !stopWords.contains(word.toLowerCase()))
        .map((word) => word[0].toUpperCase())
        .join();
  }

  String get label => '$flag $displayName - ($dialCode)';

  String get fieldLabel => '$flag $dialCode';

  bool matchesQuery(String query) {
    final normalized = query.trim().toLowerCase();
    if (normalized.isEmpty) return true;
    return name.toLowerCase().contains(normalized) ||
        displayName.toLowerCase().contains(normalized) ||
        dialCode.contains(normalized) ||
        isoCode.toLowerCase().contains(normalized);
  }

  static List<CountryDialCode> search(String query) {
    final normalized = query.trim().toLowerCase();
    if (normalized.isEmpty) return all;
    return all.where((country) => country.matchesQuery(normalized)).toList();
  }

  static const List<CountryDialCode> all = [
CountryDialCode(isoCode: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫'),
  CountryDialCode(isoCode: 'AL', name: 'Albania', dialCode: '+355', flag: '🇦🇱'),
  CountryDialCode(isoCode: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿'),
  CountryDialCode(isoCode: 'AS', name: 'American Samoa', dialCode: '+1684', flag: '🇦🇸'),
  CountryDialCode(isoCode: 'AD', name: 'Andorra', dialCode: '+376', flag: '🇦🇩'),
  CountryDialCode(isoCode: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴'),
  CountryDialCode(isoCode: 'AI', name: 'Anguilla', dialCode: '+1264', flag: '🇦🇮'),
  CountryDialCode(isoCode: 'AQ', name: 'Antarctica', dialCode: '+672', flag: '🇦🇶'),
  CountryDialCode(isoCode: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', flag: '🇦🇬'),
  CountryDialCode(isoCode: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷'),
  CountryDialCode(isoCode: 'AM', name: 'Armenia', dialCode: '+374', flag: '🇦🇲'),
  CountryDialCode(isoCode: 'AW', name: 'Aruba', dialCode: '+297', flag: '🇦🇼'),
  CountryDialCode(isoCode: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺'),
  CountryDialCode(isoCode: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹'),
  CountryDialCode(isoCode: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿'),
  CountryDialCode(isoCode: 'BS', name: 'Bahamas', dialCode: '+1242', flag: '🇧🇸'),
  CountryDialCode(isoCode: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭'),
  CountryDialCode(isoCode: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩'),
  CountryDialCode(isoCode: 'BB', name: 'Barbados', dialCode: '+1246', flag: '🇧🇧'),
  CountryDialCode(isoCode: 'BY', name: 'Belarus', dialCode: '+375', flag: '🇧🇾'),
  CountryDialCode(isoCode: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪'),
  CountryDialCode(isoCode: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿'),
  CountryDialCode(isoCode: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯'),
  CountryDialCode(isoCode: 'BM', name: 'Bermuda', dialCode: '+1441', flag: '🇧🇲'),
  CountryDialCode(isoCode: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹'),
  CountryDialCode(isoCode: 'BO', name: 'Bolivia', dialCode: '+591', flag: '🇧🇴'),
  CountryDialCode(isoCode: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦'),
  CountryDialCode(isoCode: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼'),
  CountryDialCode(isoCode: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷'),
  CountryDialCode(isoCode: 'IO', name: 'British Indian Ocean Territory', dialCode: '+246', flag: '🇮🇴'),
  CountryDialCode(isoCode: 'VG', name: 'British Virgin Islands', dialCode: '+1284', flag: '🇻🇬'),
  CountryDialCode(isoCode: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳'),
  CountryDialCode(isoCode: 'BG', name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬'),
  CountryDialCode(isoCode: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫'),
  CountryDialCode(isoCode: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮'),
  CountryDialCode(isoCode: 'KH', name: 'Cambodia', dialCode: '+855', flag: '🇰🇭'),
  CountryDialCode(isoCode: 'CM', name: 'Cameroon', dialCode: '+237', flag: '🇨🇲'),
  CountryDialCode(isoCode: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦'),
  CountryDialCode(isoCode: 'CV', name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻'),
  CountryDialCode(isoCode: 'KY', name: 'Cayman Islands', dialCode: '+1345', flag: '🇰🇾'),
  CountryDialCode(isoCode: 'CF', name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫'),
  CountryDialCode(isoCode: 'TD', name: 'Chad', dialCode: '+235', flag: '🇹🇩'),
  CountryDialCode(isoCode: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱'),
  CountryDialCode(isoCode: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳'),
  CountryDialCode(isoCode: 'CX', name: 'Christmas Island', dialCode: '+61', flag: '🇨🇽'),
  CountryDialCode(isoCode: 'CC', name: 'Cocos Islands', dialCode: '+61', flag: '🇨🇨'),
  CountryDialCode(isoCode: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴'),
  CountryDialCode(isoCode: 'KM', name: 'Comoros', dialCode: '+269', flag: '🇰🇲'),
  CountryDialCode(isoCode: 'CG', name: 'Congo', dialCode: '+242', flag: '🇨🇬'),
  CountryDialCode(isoCode: 'CK', name: 'Cook Islands', dialCode: '+682', flag: '🇨🇰'),
  CountryDialCode(isoCode: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷'),
  CountryDialCode(isoCode: 'HR', name: 'Croatia', dialCode: '+385', flag: '🇭🇷'),
  CountryDialCode(isoCode: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺'),
  CountryDialCode(isoCode: 'CW', name: 'Curaçao', dialCode: '+599', flag: '🇨🇼'),
  CountryDialCode(isoCode: 'CY', name: 'Cyprus', dialCode: '+357', flag: '🇨🇾'),
  CountryDialCode(isoCode: 'CZ', name: 'Czechia', dialCode: '+420', flag: '🇨🇿'),
  CountryDialCode(isoCode: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰'),
  CountryDialCode(isoCode: 'DJ', name: 'Djibouti', dialCode: '+253', flag: '🇩🇯'),
  CountryDialCode(isoCode: 'DM', name: 'Dominica', dialCode: '+1767', flag: '🇩🇲'),
  CountryDialCode(isoCode: 'DO', name: 'Dominican Republic', dialCode: '+1809', flag: '🇩🇴'),
  CountryDialCode(isoCode: 'CD', name: 'DR Congo', dialCode: '+243', flag: '🇨🇩'),
  CountryDialCode(isoCode: 'EC', name: 'Ecuador', dialCode: '+593', flag: '🇪🇨'),
  CountryDialCode(isoCode: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬'),
  CountryDialCode(isoCode: 'SV', name: 'El Salvador', dialCode: '+503', flag: '🇸🇻'),
  CountryDialCode(isoCode: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶'),
  CountryDialCode(isoCode: 'ER', name: 'Eritrea', dialCode: '+291', flag: '🇪🇷'),
  CountryDialCode(isoCode: 'EE', name: 'Estonia', dialCode: '+372', flag: '🇪🇪'),
  CountryDialCode(isoCode: 'SZ', name: 'Eswatini', dialCode: '+268', flag: '🇸🇿'),
  CountryDialCode(isoCode: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹'),
  CountryDialCode(isoCode: 'FK', name: 'Falkland Islands', dialCode: '+500', flag: '🇫🇰'),
  CountryDialCode(isoCode: 'FO', name: 'Faroe Islands', dialCode: '+298', flag: '🇫🇴'),
  CountryDialCode(isoCode: 'FJ', name: 'Fiji', dialCode: '+679', flag: '🇫🇯'),
  CountryDialCode(isoCode: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮'),
  CountryDialCode(isoCode: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷'),
  CountryDialCode(isoCode: 'GF', name: 'French Guiana', dialCode: '+594', flag: '🇬🇫'),
  CountryDialCode(isoCode: 'PF', name: 'French Polynesia', dialCode: '+689', flag: '🇵🇫'),
  CountryDialCode(isoCode: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦'),
  CountryDialCode(isoCode: 'GM', name: 'Gambia', dialCode: '+220', flag: '🇬🇲'),
  CountryDialCode(isoCode: 'GE', name: 'Georgia', dialCode: '+995', flag: '🇬🇪'),
  CountryDialCode(isoCode: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪'),
  CountryDialCode(isoCode: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭'),
  CountryDialCode(isoCode: 'GI', name: 'Gibraltar', dialCode: '+350', flag: '🇬🇮'),
  CountryDialCode(isoCode: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷'),
  CountryDialCode(isoCode: 'GL', name: 'Greenland', dialCode: '+299', flag: '🇬🇱'),
  CountryDialCode(isoCode: 'GD', name: 'Grenada', dialCode: '+1473', flag: '🇬🇩'),
  CountryDialCode(isoCode: 'GP', name: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵'),
  CountryDialCode(isoCode: 'GU', name: 'Guam', dialCode: '+1671', flag: '🇬🇺'),
  CountryDialCode(isoCode: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹'),
  CountryDialCode(isoCode: 'GG', name: 'Guernsey', dialCode: '+44', flag: '🇬🇬'),
  CountryDialCode(isoCode: 'GN', name: 'Guinea', dialCode: '+224', flag: '🇬🇳'),
  CountryDialCode(isoCode: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼'),
  CountryDialCode(isoCode: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾'),
  CountryDialCode(isoCode: 'HT', name: 'Haiti', dialCode: '+509', flag: '🇭🇹'),
  CountryDialCode(isoCode: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳'),
  CountryDialCode(isoCode: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰'),
  CountryDialCode(isoCode: 'HU', name: 'Hungary', dialCode: '+36', flag: '🇭🇺'),
  CountryDialCode(isoCode: 'IS', name: 'Iceland', dialCode: '+354', flag: '🇮🇸'),
  CountryDialCode(isoCode: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳'),
  CountryDialCode(isoCode: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩'),
  CountryDialCode(isoCode: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷'),
  CountryDialCode(isoCode: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶'),
  CountryDialCode(isoCode: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪'),
  CountryDialCode(isoCode: 'IM', name: 'Isle of Man', dialCode: '+44', flag: '🇮🇲'),
  CountryDialCode(isoCode: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱'),
  CountryDialCode(isoCode: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹'),
  CountryDialCode(isoCode: 'CI', name: 'Ivory Coast', dialCode: '+225', flag: '🇨🇮'),
  CountryDialCode(isoCode: 'JM', name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲'),
  CountryDialCode(isoCode: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵'),
  CountryDialCode(isoCode: 'JE', name: 'Jersey', dialCode: '+44', flag: '🇯🇪'),
  CountryDialCode(isoCode: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴'),
  CountryDialCode(isoCode: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿'),
  CountryDialCode(isoCode: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪'),
  CountryDialCode(isoCode: 'KI', name: 'Kiribati', dialCode: '+686', flag: '🇰🇮'),
  CountryDialCode(isoCode: 'XK', name: 'Kosovo', dialCode: '+383', flag: '🇽🇰'),
  CountryDialCode(isoCode: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼'),
  CountryDialCode(isoCode: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flag: '🇰🇬'),
  CountryDialCode(isoCode: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦'),
  CountryDialCode(isoCode: 'LV', name: 'Latvia', dialCode: '+371', flag: '🇱🇻'),
  CountryDialCode(isoCode: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧'),
  CountryDialCode(isoCode: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸'),
  CountryDialCode(isoCode: 'LR', name: 'Liberia', dialCode: '+231', flag: '🇱🇷'),
  CountryDialCode(isoCode: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾'),
  CountryDialCode(isoCode: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮'),
  CountryDialCode(isoCode: 'LT', name: 'Lithuania', dialCode: '+370', flag: '🇱🇹'),
  CountryDialCode(isoCode: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺'),
  CountryDialCode(isoCode: 'MO', name: 'Macau', dialCode: '+853', flag: '🇲🇴'),
  CountryDialCode(isoCode: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬'),
  CountryDialCode(isoCode: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼'),
  CountryDialCode(isoCode: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾'),
  CountryDialCode(isoCode: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻'),
  CountryDialCode(isoCode: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱'),
  CountryDialCode(isoCode: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹'),
  CountryDialCode(isoCode: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭'),
  CountryDialCode(isoCode: 'MQ', name: 'Martinique', dialCode: '+596', flag: '🇲🇶'),
  CountryDialCode(isoCode: 'MR', name: 'Mauritania', dialCode: '+222', flag: '🇲🇷'),
  CountryDialCode(isoCode: 'MU', name: 'Mauritius', dialCode: '+230', flag: '🇲🇺'),
  CountryDialCode(isoCode: 'YT', name: 'Mayotte', dialCode: '+262', flag: '🇾🇹'),
  CountryDialCode(isoCode: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽'),
  CountryDialCode(isoCode: 'FM', name: 'Micronesia', dialCode: '+691', flag: '🇫🇲'),
  CountryDialCode(isoCode: 'MD', name: 'Moldova', dialCode: '+373', flag: '🇲🇩'),
  CountryDialCode(isoCode: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨'),
  CountryDialCode(isoCode: 'MN', name: 'Mongolia', dialCode: '+976', flag: '🇲🇳'),
  CountryDialCode(isoCode: 'ME', name: 'Montenegro', dialCode: '+382', flag: '🇲🇪'),
  CountryDialCode(isoCode: 'MS', name: 'Montserrat', dialCode: '+1664', flag: '🇲🇸'),
  CountryDialCode(isoCode: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦'),
  CountryDialCode(isoCode: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿'),
  CountryDialCode(isoCode: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲'),
  CountryDialCode(isoCode: 'NA', name: 'Namibia', dialCode: '+264', flag: '🇳🇦'),
  CountryDialCode(isoCode: 'NR', name: 'Nauru', dialCode: '+674', flag: '🇳🇷'),
  CountryDialCode(isoCode: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵'),
  CountryDialCode(isoCode: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱'),
  CountryDialCode(isoCode: 'NC', name: 'New Caledonia', dialCode: '+687', flag: '🇳🇨'),
  CountryDialCode(isoCode: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿'),
  CountryDialCode(isoCode: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮'),
  CountryDialCode(isoCode: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪'),
  CountryDialCode(isoCode: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬'),
  CountryDialCode(isoCode: 'NU', name: 'Niue', dialCode: '+683', flag: '🇳🇺'),
  CountryDialCode(isoCode: 'NF', name: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫'),
  CountryDialCode(isoCode: 'KP', name: 'North Korea', dialCode: '+850', flag: '🇰🇵'),
  CountryDialCode(isoCode: 'MK', name: 'North Macedonia', dialCode: '+389', flag: '🇲🇰'),
  CountryDialCode(isoCode: 'MP', name: 'Northern Mariana Islands', dialCode: '+1670', flag: '🇲🇵'),
  CountryDialCode(isoCode: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴'),
  CountryDialCode(isoCode: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲'),
  CountryDialCode(isoCode: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰'),
  CountryDialCode(isoCode: 'PW', name: 'Palau', dialCode: '+680', flag: '🇵🇼'),
  CountryDialCode(isoCode: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸'),
  CountryDialCode(isoCode: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦'),
  CountryDialCode(isoCode: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬'),
  CountryDialCode(isoCode: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾'),
  CountryDialCode(isoCode: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪'),
  CountryDialCode(isoCode: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭'),
  CountryDialCode(isoCode: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱'),
  CountryDialCode(isoCode: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹'),
  CountryDialCode(isoCode: 'PR', name: 'Puerto Rico', dialCode: '+1787', flag: '🇵🇷'),
  CountryDialCode(isoCode: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦'),
  CountryDialCode(isoCode: 'RE', name: 'Réunion', dialCode: '+262', flag: '🇷🇪'),
  CountryDialCode(isoCode: 'RO', name: 'Romania', dialCode: '+40', flag: '🇷🇴'),
  CountryDialCode(isoCode: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺'),
  CountryDialCode(isoCode: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼'),
  CountryDialCode(isoCode: 'BL', name: 'Saint Barthélemy', dialCode: '+590', flag: '🇧🇱'),
  CountryDialCode(isoCode: 'SH', name: 'Saint Helena', dialCode: '+290', flag: '🇸🇭'),
  CountryDialCode(isoCode: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', flag: '🇰🇳'),
  CountryDialCode(isoCode: 'LC', name: 'Saint Lucia', dialCode: '+1758', flag: '🇱🇨'),
  CountryDialCode(isoCode: 'MF', name: 'Saint Martin', dialCode: '+590', flag: '🇲🇫'),
  CountryDialCode(isoCode: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', flag: '🇵🇲'),
  CountryDialCode(isoCode: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1784', flag: '🇻🇨'),
  CountryDialCode(isoCode: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸'),
  CountryDialCode(isoCode: 'SM', name: 'San Marino', dialCode: '+378', flag: '🇸🇲'),
  CountryDialCode(isoCode: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', flag: '🇸🇹'),
  CountryDialCode(isoCode: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦'),
  CountryDialCode(isoCode: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳'),
  CountryDialCode(isoCode: 'RS', name: 'Serbia', dialCode: '+381', flag: '🇷🇸'),
  CountryDialCode(isoCode: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨'),
  CountryDialCode(isoCode: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱'),
  CountryDialCode(isoCode: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬'),
  CountryDialCode(isoCode: 'SX', name: 'Sint Maarten', dialCode: '+1721', flag: '🇸🇽'),
  CountryDialCode(isoCode: 'SK', name: 'Slovakia', dialCode: '+421', flag: '🇸🇰'),
  CountryDialCode(isoCode: 'SI', name: 'Slovenia', dialCode: '+386', flag: '🇸🇮'),
  CountryDialCode(isoCode: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧'),
  CountryDialCode(isoCode: 'SO', name: 'Somalia', dialCode: '+252', flag: '🇸🇴'),
  CountryDialCode(isoCode: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦'),
  CountryDialCode(isoCode: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷'),
  CountryDialCode(isoCode: 'SS', name: 'South Sudan', dialCode: '+211', flag: '🇸🇸'),
  CountryDialCode(isoCode: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸'),
  CountryDialCode(isoCode: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰'),
  CountryDialCode(isoCode: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩'),
  CountryDialCode(isoCode: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷'),
  CountryDialCode(isoCode: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪'),
  CountryDialCode(isoCode: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭'),
  CountryDialCode(isoCode: 'SY', name: 'Syria', dialCode: '+963', flag: '🇸🇾'),
  CountryDialCode(isoCode: 'TW', name: 'Taiwan', dialCode: '+886', flag: '🇹🇼'),
  CountryDialCode(isoCode: 'TJ', name: 'Tajikistan', dialCode: '+992', flag: '🇹🇯'),
  CountryDialCode(isoCode: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿'),
  CountryDialCode(isoCode: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭'),
  CountryDialCode(isoCode: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱'),
  CountryDialCode(isoCode: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬'),
  CountryDialCode(isoCode: 'TK', name: 'Tokelau', dialCode: '+690', flag: '🇹🇰'),
  CountryDialCode(isoCode: 'TO', name: 'Tonga', dialCode: '+676', flag: '🇹🇴'),
  CountryDialCode(isoCode: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹'),
  CountryDialCode(isoCode: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳'),
  CountryDialCode(isoCode: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷'),
  CountryDialCode(isoCode: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: '🇹🇲'),
  CountryDialCode(isoCode: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1649', flag: '🇹🇨'),
  CountryDialCode(isoCode: 'TV', name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻'),
  CountryDialCode(isoCode: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬'),
  CountryDialCode(isoCode: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦'),
  CountryDialCode(isoCode: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪'),
  CountryDialCode(isoCode: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧'),
  CountryDialCode(isoCode: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸'),
  CountryDialCode(isoCode: 'VI', name: 'US Virgin Islands', dialCode: '+1340', flag: '🇻🇮'),
  CountryDialCode(isoCode: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾'),
  CountryDialCode(isoCode: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿'),
  CountryDialCode(isoCode: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺'),
  CountryDialCode(isoCode: 'VA', name: 'Vatican City', dialCode: '+379', flag: '🇻🇦'),
  CountryDialCode(isoCode: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪'),
  CountryDialCode(isoCode: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳'),
  CountryDialCode(isoCode: 'WF', name: 'Wallis and Futuna', dialCode: '+681', flag: '🇼🇫'),
  CountryDialCode(isoCode: 'EH', name: 'Western Sahara', dialCode: '+212', flag: '🇪🇭'),
  CountryDialCode(isoCode: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪'),
  CountryDialCode(isoCode: 'ZM', name: 'Zambia', dialCode: '+260', flag: '🇿🇲'),
  CountryDialCode(isoCode: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼'),
  ];

  static CountryDialCode? findByDialCode(String dialCode) {
    for (final country in all) {
      if (country.dialCode == dialCode) return country;
    }
    return null;
  }

  static CountryDialCode? findByIsoCode(String isoCode) {
    for (final country in all) {
      if (country.isoCode == isoCode) return country;
    }
    return null;
  }
}
